server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: gateway-0 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 40 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: service-gateway #此实例注册到eureka服务端的name
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://SERVICE-USER
          predicates:
            #- Cookie=login, user-1
            - Query=name,1
            - Query=age
            - Path=/**
          filters:
            - name: Hystrix
              args:
                name: fallback
                fallbackUri: forward:/fallback

          #
          #
          #
          #
          ##      circuitBreaker:
          ##        requestVolumeThreshold: 5
          ##        sleepWindowInMilliseconds : 5000   时间
